name: scan_snap
description: A Flutter QR/barcode scanner widget with camera view and image parsing.
version: 0.1.2
homepage: https://github.com/gearscrafter/scan_snap
repository: https://github.com/gearscrafter/scan_snap
issue_tracker: https://github.com/gearscrafter/scan_snap/issues
topics:
  - qr
  - scanner
  - camera
  - image
  - spm
  
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.gearscrafter.scan_snap
        pluginClass: ScanPlugin
      ios:
        pluginClass: ScanPlugin

license: MIT
